

import argparse
import base64
import json
import sys
import time
from pathlib import Path

import requests

# ── CONFIGURATION ──────────────────────────────────────────────────────────

DEFAULT_MODEL   = "qwen2.5vl:7b"
OLLAMA_BASE_URL = "http://localhost:11434"
SLEEP_BETWEEN   = 0.5   # seconds between calls — avoids hammering the GPU

SYSTEM_PROMPT = """\
You are an expert analytical chemist specialising in polymer characterisation
by Liquid Chromatography at Critical Conditions (LCCC).

Analyse the provided figure or table image (and its caption if given) from a
scientific paper. Extract every piece of information relevant to LCCC or
related polymer chromatography.

Return ONLY valid JSON — no markdown fences, no preamble — matching this schema:

{
  "is_lccc_relevant": true | false,
  "summary": "<one sentence describing what the image shows>",
  "lccc_conditions": {
    "stationary_phase":          null | "<string>",
    "mobile_phase":              null | "<string, e.g. acetonitrile/THF 60:40>",
    "temperature_celsius":       null | <number>,
    "flow_rate_ml_per_min":      null | <number>,
    "column_dimensions":         null | "<string>",
    "critical_point_described":  null | "<string>",
    "gradient_or_isocratic":     null | "<string>"
  },
  "polymer_info": {
    "polymer_type":      null | "<string, e.g. PMMA, PEO, PS-b-PEO>",
    "molecular_weight":  null | "<string, e.g. Mn=15 kDa>",
    "dispersity_Mw_Mn": null | "<string>",
    "architecture":      null | "<string, e.g. block, star, blend>"
  },
  "detector_info":  null | "<string, e.g. ELSD, UV 254 nm, RI>",
  "other_findings": null | "<any other relevant analytical detail>"
}

If the image has no LCCC-relevant content set is_lccc_relevant to false and
leave all other fields null. Never invent data — only report what is
explicitly visible in the image or caption.\
"""


# ── HELPERS ────────────────────────────────────────────────────────────────

def load_b64(path: Path):
    if not path.exists():
        print(f"  WARNING: Missing file: {path}", file=sys.stderr)
        return None
    with open(path, "rb") as fh:
        return base64.b64encode(fh.read()).decode()


def build_pairs(links: list) -> list:
    """Match each figure/table to its linked caption."""
    by_key = {(e["page"], e["index"]): e for e in links}
    pairs = []
    for item in links:
        if item["type"] not in ("figure", "table"):
            continue
        cap = None
        if "linked_caption" in item:
            lc = item["linked_caption"]
            cap = by_key.get((lc["page"], lc["index"]))
        pairs.append({"main": item, "caption": cap})
    return pairs


def call_ollama(model: str, images_b64: list, prompt: str, base_url: str) -> str:
    payload = {
        "model":  model,
        "system": SYSTEM_PROMPT,
        "prompt": prompt,
        "images": images_b64,
        "stream": False,
        "options": {"temperature": 0.1, "num_predict": 1024},
    }
    resp = requests.post(f"{base_url}/api/generate", json=payload, timeout=180)
    resp.raise_for_status()
    return resp.json()["response"].strip()


def parse_json(raw: str) -> dict:
    text = raw
    if "```" in text:
        for part in text.split("```"):
            c = part.strip().lstrip("json").strip()
            if c.startswith("{"):
                text = c
                break
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        return {"error": "JSON parse failed", "raw_response": raw}


def analyse_pair(model: str, base_dir: Path, pair: dict, base_url: str) -> dict:
    main, cap = pair["main"], pair["caption"]
    images, labels = [], []

    if cap:
        b = load_b64(base_dir / cap["file"])
        if b:
            images.append(b)
            labels.append("Image 1: Caption")

    mb = load_b64(base_dir / main["file"])
    if mb is None:
        return {"error": f"Could not load {main['file']}"}
    images.append(mb)
    labels.append(f"Image {len(images)}: {main['type'].capitalize()} (page {main['page']})")

    prompt = "\n".join(labels) + "\n\nExtract all LCCC-relevant information. Return JSON only."
    return parse_json(call_ollama(model, images, prompt, base_url))


# ── MARKDOWN REPORT ────────────────────────────────────────────────────────

def write_markdown(results: list, out_path: Path):
    lines = ["# LCCC Extraction Report\n\n_Auto-generated by extract_lccc.py_\n\n---\n\n"]
    relevant = [r for r in results if r["extraction"].get("is_lccc_relevant")]
    errors   = [r for r in results if "error" in r["extraction"]]
    lines += [
        f"**Items analysed:** {len(results)}  \n",
        f"**LCCC-relevant:** {len(relevant)}  \n",
        f"**Errors:** {len(errors)}  \n\n---\n\n",
    ]

    for r in results:
        m, ext = r["item"], r["extraction"]
        lines.append(f"## Page {m['page']} — {m['type'].capitalize()} #{m['index']}\n\n")
        lines.append(f"`{m['file']}`\n\n")

        if "error" in ext:
            lines.append(f"> ERROR: {ext['error']}\n\n---\n\n")
            continue
        if not ext.get("is_lccc_relevant"):
            lines.append("_Not LCCC-relevant._\n\n---\n\n")
            continue

        if ext.get("summary"):
            lines.append(f"**Summary:** {ext['summary']}\n\n")

        for section, header in [("lccc_conditions", "Chromatographic Conditions"),
                                  ("polymer_info",    "Polymer Information")]:
            data = ext.get(section) or {}
            rows = [(k.replace("_", " ").title(), v) for k, v in data.items() if v is not None]
            if rows:
                lines.append(f"### {header}\n\n| Parameter | Value |\n|---|---|\n")
                lines += [f"| {k} | {v} |\n" for k, v in rows]
                lines.append("\n")

        for field in ("detector_info", "other_findings"):
            if ext.get(field):
                lines.append(f"**{field.replace('_',' ').title()}:** {ext[field]}  \n")

        lines.append("\n---\n\n")

    out_path.write_text("".join(lines), encoding="utf-8")
    print(f"Markdown report -> {out_path}")


# ── MAIN ───────────────────────────────────────────────────────────────────

def main():
    ap = argparse.ArgumentParser(
        description="Extract polymer LCCC conditions from paper figures/tables using Ollama."
    )
    ap.add_argument("--base-dir",   required=True, help="Folder with figure/ table/ caption/ subfolders")
    ap.add_argument("--links",      required=True, help="JSON linking file")
    ap.add_argument("--model",      default=DEFAULT_MODEL, help=f"Ollama model (default: {DEFAULT_MODEL})")
    ap.add_argument("--output-dir", default=".", help="Output directory")
    ap.add_argument("--ollama-url", default=OLLAMA_BASE_URL, help=f"Ollama URL (default: {OLLAMA_BASE_URL})")
    args = ap.parse_args()

    base_dir   = Path(args.base_dir)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    with open(args.links, encoding="utf-8") as fh:
        links = json.load(fh)

    pairs = build_pairs(links)
    print(f"Found {len(pairs)} figure/table items — model: {args.model}\n")

    results = []
    for i, pair in enumerate(pairs, 1):
        m = pair["main"]
        print(f"  [{i}/{len(pairs)}] Page {m['page']} {m['type']} #{m['index']} ...", end=" ", flush=True)
        try:
            ext = analyse_pair(args.model, base_dir, pair, args.ollama_url)
            print("LCCC!" if ext.get("is_lccc_relevant") else "-")
        except Exception as exc:
            ext = {"error": str(exc)}
            print(f"ERROR: {exc}")
        results.append({"item": m, "extraction": ext})
        time.sleep(SLEEP_BETWEEN)

    json_out = output_dir / "lccc_results.json"
    with open(json_out, "w", encoding="utf-8") as fh:
        json.dump(results, fh, indent=2)
    print(f"\nJSON results -> {json_out}")

    write_markdown(results, output_dir / "lccc_summary.md")

    relevant = [r for r in results if r["extraction"].get("is_lccc_relevant")]
    print(f"\n{'─'*52}\nLCCC-relevant: {len(relevant)} / {len(results)}")
    for r in relevant:
        m = r["item"]
        print(f"  Page {m['page']} {m['type']} #{m['index']}: {r['extraction'].get('summary','')}")


if __name__ == "__main__":
    main()